# Now that we have our cleaned dataframes, let's do some classification

In [119]:
#Imports
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split, GridSearchCV

In [2]:
covid_df = pd.read_csv('./data/clean_covid_data.csv')
gas_df = pd.read_csv('./data/gas_stations.csv')

In [10]:
covid_df.head(2)

,date,county,fips,place,confirmed_cases,note,x,y,log_cases,category,ordinal_cat
0,2020-10-23,Sonoma,97.0,Bodega,1,10 or fewer,-122.973889,38.345278,0.0,0,0
1,2020-07-02,Plumas,63.0,Indian Valley,1,NaN,-120.885787,40.081003,0.0,0,0

In [11]:
gas_df.head(2)

                  name   longitude   latitude
0  Circle K & Minimart -117.190777  34.057365
1                  NaN -117.225609  34.048575

In [ ]:
# train/test/split with just covid data (labeled dataset)

In [ ]:
X = covid_df[['x', 'y']]
y_cat = covid_df['ordinal_cat'] #for when we do our categorical classification
y_cts = covid_df['log_cases'] #for when we do regression based on

# New Idea: do hand-done PCA

In [16]:
#just using bottom 5 as an example
df = covid_df.tail()
df

,date,county,fips,place,confirmed_cases,note,x,y,log_cases,category,ordinal_cat
1200,2020-10-25,Los Angeles,37.0,Long Beach,13013,NaN,-118.161014,33.805559,9.473704,4,4
1201,2020-10-23,Sacramento,67.0,Sacramento,14476,NaN,-121.494444,38.581667,9.580247,4,4
1202,2020-10-25,Santa Clara,85.0,San Jose,15817,NaN,-121.900000,37.333333,9.668841,4,4
1203,2020-10-23,Fresno,19.0,Fresno,17052,NaN,-119.766667,36.750000,9.744023,4,4
1204,2020-10-25,San Diego,73.0,San Diego,23644,NaN,-117.148962,32.692470,10.070865,4,4

In [49]:
def find_closest_points(target_point, df, num_points):
    #break target into x and y
    x_target = target[0]
    y_target = target[1]
    
    # for each row in the dataframe (can't really iterate)
    # first need to make these columns as lists so we can iterate
    df_xlist = df['x'].tolist()
    df_ylist = df['y'].tolist()
    
    distances = []
    for x in range(len(df_xlist)):
        
        #change in x and y for the stop and start coords
        delta_x = df_xlist[x] - x_target
        delta_y = df_ylist[x] - y_target
        #distance between start and stop
        d = np.sqrt((delta_x)**2 + (delta_y)**2)
        distances.append(d)
    
    #df['distances'] = distances # gave me a copy error
    new_df = df.copy()
    new_df['distances'] = distances
    new_df = new_df.sort_values(by = 'distances')
    
    # need to make sure we don't count the target point (get 1:4 instead of :3)
    return new_df[1:4]

In [87]:
# just choose a random point from the dataframe to visualize what's happening
target_x = float(covid_df.iloc[[-5]]['x']) 
target_y = float(covid_df.iloc[[-5]]['y'])
target = (target_x, target_y)

In [90]:
find_closest_points(target_point = target, df = covid_df, num_points = 3)['distances'].tolist()

[0.007691419959931177, 0.008555378717510472, 0.02343421790885981]

In [93]:
def get_alpha_for_target_point(target_point, df, num_points):
    
    # can't loop over length of dataframe, so I'll put the distances of the relevant points in a list
    distances = find_closest_points(target_point = target_point, df = df, num_points = num_points)['distances'].tolist()
    
    # and put their corresponding log_cases in a list
    log_cases = find_closest_points(target_point = target_point, df = df, num_points = num_points)['log_cases'].tolist()
    
    alpha = 0
    for x in range(len(distances)):
        if distances[x] != 0:
            alpha += log_cases[x]/distances[x]
        else:
            alpha +=0
    
    return alpha

In [94]:
get_alpha_for_target_point(target_point = target, df = covid_df, num_points = 3)

1358.9412730995564

In [95]:
# create column in dataframe of these alphas
covid_df_xlist = covid_df['x']
covid_df_ylist = covid_df['y']

alphas = []

n_neighbors = 3

for x in range(len(covid_df_xlist)):
    target = (covid_df_xlist[x], covid_df_ylist[x])
    alpha = get_alpha_for_target_point(target_point = target, df = covid_df, num_points = n_neighbors)
    alphas.append(alpha)
    
alphas

[84.2446036442287,
 44.51616212092759,
 86.90439832836414,
 148.81373530182626,
 52.84439889181487,
 6.727057359677954,
 226.39550280759843,
 65.52287190101812,
 1212.8816335490978,
 63.7535062121234,
 23.25443914314826,
 150.82839499038036,
 0.0,
 92.92913098485712,
 0.0,
 78.41254334867277,
 88.44516034525753,
 591.5280885415478,
 1263.3996554134214,
 103.84119228560166,
 120.684619693045,
 260.6769055873673,
 104.24398380440383,
 0.0,
 19.9634369051365,
 364.0012133210347,
 41.39509156848929,
 0.0,
 133.75754373397734,
 243.68288944030672,
 44.7698857817648,
 65.26801889642167,
 317.6130744339286,
 64.14556490364214,
 51.8716251937164,
 135.5390541609989,
 195.73519901054027,
 24.827597220726634,
 242.00103705040942,
 135.448397712372,
 34.63074807768131,
 0.0,
 438.5658590599876,
 77.05037410174596,
 243.68288944030672,
 20.998083947008517,
 4507.224895508925,
 49.115334606647615,
 1522.7392116236647,
 276.2827322937985,
 239.0874152450091,
 515.9117224826045,
 84.35578560494068,
 334.11864843561295,
 356.1853658269333,
 165.68167477290982,
 17.30061908982218,
 77.55883190622106,
 64.34513410804092,
 69.87168387854297,
 824.6930100224324,
 25.445194060540334,
 72.04227624536453,
 542.9444614342049,
 36.825132522235904,
 68.43223009236219,
 264.757945595863,
 136.2177383970531,
 30.375395338653856,
 12.18857485302261,
 8.39425033755787,
 48.19981589685018,
 116.95278781908547,
 512.127397743712,
 45.65628499812857,
 2205.8116746347355,
 31.895534066093752,
 133.82060967293805,
 229.66087231736253,
 453.30035572988675,
 60.7242653464307,
 63.274929518611025,
 11.660922780521144,
 99.54034862727424,
 16.22336758917941,
 82.34835523274185,
 1035.5674681812066,
 37.17552832527616,
 463.48422007401643,
 22.853200353812557,
 473.4898070841666,
 299.1839457731208,
 35.96042304947304,
 176.99139983154078,
 341.95768771928266,
 737.8790075614381,
 185.436827460762,
 74.62150139886398,
 161.8333574627307,
 703.2581742515622,
 69.49034532939253,
 141.35523173532619,
 1955.9665247008504,
 679.9801300511344,
 73.49395442692864,
 87.4921650082497,
 106.05674377980634,
 130.2167121136523,
 195.9100960244521,
 5309.643733261684,
 518.6387939926944,
 178.714909439469,
 855.7488721287796,
 67.05087394284443,
 126.91243177002085,
 453.38309010798184,
 76.93518804327387,
 457.35623340672475,
 1199.3859493994864,
 124.16431936516258,
 32.84741904010562,
 545.8556200299699,
 5.142649138723171,
 96.52646385090252,
 1845.1733368910961,
 233.2393731031867,
 58.32925191455757,
 3308.8496927075075,
 182.6633403559153,
 40.25341796141326,
 161.5065418432818,
 44.35749499672571,
 25.35861920865209,
 88.67795111794243,
 161.5065418432818,
 74.08121645559602,
 33.29479196326968,
 67.42700106064542,
 202.11385305515486,
 88.49739959266131,
 224.45492278228195,
 75.59576812014902,
 50.66194047209106,
 706.7698772623877,
 198.13376204594914,
 32.84741904010562,
 498.9586984563754,
 61.89532510526844,
 1188.9974438269032,
 364.25175677383936,
 530.4365097473905,
 97.94975493165202,
 730.4039457538125,
 49.995919260734595,
 48.185361207915726,
 87.20258410014964,
 731.7852416591755,
 33.22794326450005,
 138.952681755055,
 13.808678775907426,
 662.715102697336,
 341.9372110825366,
 76.79007830388645,
 816.4473358083222,
 44.21993252114865,
 31.211844461621997,
 481.96169214699603,
 48.18547998833459,
 34.66174608344425,
 91.37283741954673,
 237.73099814452397,
 65.34336239689051,
 31.020485886757275,
 859.3258275578313,
 316.8366661965564,
 556.7025661991042,
 70.28557116216176,
 58.528810942183924,
 362.2377693175889,
 205.74787001542802,
 70.58160362635944,
 353.591329880397,
 663.7121603575604,
 771.1534904329376,
 819.0351965184733,
 127.21729077504486,
 238.86294095296284,
 166.6957590063506,
 118.01840624521057,
 276.19622700736915,
 161.71703963549737,
 391.799662005725,
 7.263965918188003,
 189.68460129636364,
 194.1948129448079,
 26.964644833652116,
 276.9791879094807,
 23.616529674541052,
 50.93415123618729,
 889.6557655348736,
 245.1531641915666,
 44.83608912111843,
 292.65539398183626,
 14699.989168902366,
 146.90354673094518,
 71.8979642044457,
 5833.287536493943,
 156.4194732297098,
 312.05294424318976,
 2132.1360589887136,
 69.6224679386717,
 152.10019812116462,
 391.670501926797,
 175.2629165907806,
 49.2570722632771,
 28.252468529605803,
 288.38702647066276,
 357.016308139988,
 6.727057359677954,
 781.2817325583774,
 91.40573913100867,
 30.365258346316104,
 102.68060304925115,
 276.4595380291365,
 17.888587562130965,
 55.849477564140926,
 53.34487181565489,
 118.01840624521057,
 67.99289579072948,
 184.59821182521154,
 338.45500181763293,
 105.62633607173191,
 232.36767362700334,
 257.72766790686273,
 157.45579281738046,
 17.56322843774886,
 98.43782312295325,
 46.29425796768369,
 293.5587271983103,
 205.27100169116,
 290.64504121920777,
 67.1909802311269,
 101.89264815373033,
 756.7533556363232,
 19.669368351082284,
 403.4992416921428,
 1186.3155953982143,
 74.47543702328653,
 200.94987650804921,
 94.31171480433235,
 156.4123951269466,
 229.67830978989204,
 101.82345571498081,
 202.42592860769957,
 39.16363930701728,
 26.964644833652116,
 107.47409580785956,
 146.80847144359885,
 1039.9258470407044,
 72.3469204364306,
 75.75200229772531,
 116.24251507978605,
 112.9800390024981,
 23.36334361112504,
 136.03175519785052,
 179.05698900760683,
 440.38667518476836,
 0.0,
 178.8399339429797,
 179.77173813980562,
 101.23297278391036,
 861.1653911256217,
 414.2690504400248,
 716.0594869157845,
 6.344914242791428,
 100.39987158940357,
 250.41889276543884,
 90.0203721157547,
 1150.7099316854737,
 455.45844238015326,
 16.484867284175856,
 926.6067399729681,
 466.67654528715445,
 218.39851827010585,
 76.92748277706349,
 284.8280691304543,
 60.80541017119427,
 938.6885783603757,
 92.99136940442699,
 124.26245494110525,
 66.4960401506551,
 433.3639768033532,
 207.81224384977313,
 312.39357672102847,
 652.0978635286735,
 14.446474165012468,
 40.601812384371364,
 282.37485233228057,
 59.58550677747623,
 24.84410867929263,
 15.897988931041123,
 117.00986431513338,
 127.36927069574503,
 87.29632119740492,
 449.89556870692786,
 427.4835858276678,
 84.5814076386074,
 232.92268244938825,
 283.96350597197716,
 168.47645268749469,
 79.60398878562644,
 128.32030321208487,
 150.91808928022576,
 1128.8081723168425,
 96.92077365419328,
 1519.9751187757493,
 284.9707703741542,
 93.54291434133152,
 26.772065435156073,
 127.20100991898912,
 382.1765193563655,
 90.31471756781895,
 593.5953344318503,
 1700.027065443583,
 88.81787077125274,
 39.604312037174225,
 252.30341021529586,
 721.5416126267046,
 440.60559415377827,
 1159.2929570885806,
 158.44247398830356,
 833.2668080115551,
 65.76263505195932,
 95.85547118740641,
 68.57496921026674,
 158.44247398830356,
 60.404710362224385,
 1148.0624746669805,
 781.4793696195879,
 432.20195404579664,
 195.74287348666115,
 332.54123835436184,
 121.51771705107306,
 557.7606850959679,
 63.894750460833386,
 130.45360170520496,
 45.230235003321084,
 283.3554017437503,
 381.4980222016859,
 1142.4860723193178,
 784.4271968440696,
 414.35849475738337,
 211.16384540525507,
 40.945632751662856,
 316.54580585929614,
 629.5804988951176,
 154.2998777229796,
 187.6063020443391,
 428.9679709248016,
 780.3074114724387,
 378.77137917073946,
 267.3351124106207,
 53.48960480234419,
 364.0012133210347,
 198.29119332513517,
 224.36760517444023,
 237.2411832503897,
 5.142649138723171,
 779.1043657891578,
 615.8254646266773,
 54.640777975828875,
 46.75827170982861,
 1737.6236302794173,
 118.66752422585066,
 384.05619696987685,
 72.3469204364306,
 252.30480631309777,
 1006.0844603765943,
 229.3026598416459,
 258.2611665443858,
 65.90746175028174,
 979.9346559921081,
 116.9393380856028,
 204.95342008096387,
 247.67430918621147,
 99.60266579175322,
 152.18709461424453,
 160.70122523732812,
 380.67954506700454,
 180.83474378153477,
 355.44461229153944,
 38.277784636375266,
 651.8512955879767,
 55.65066969312002,
 48.30344595463974,
 94.66058522981672,
 323.97161294065745,
 474.97295378903164,
 254.128912922876,
 484.902764780968,
 55.773620638554576,
 94.95091048393755,
 82.62002648927134,
 393.1710434439284,
 1391.343897555107,
 66.56711645612404,
 331.45161935316065,
 167.00772487223742,
 8587.258844932758,
 119.46098882853593,
 122.65564174927653,
 336.0096539266834,
 804.7317529843214,
 355.3209377420025,
 457.0002331350566,
 40.80730839924237,
 671.4870038154959,
 227.23573437498396,
 189.78187218862882,
 904.7808054612792,
 37.55445486737436,
 634.8353204258257,
 82.46542019155572,
 458.34298424763256,
 138.88148999100363,
 42.108075636300754,
 146.96055653581163,
 79.07291146356114,
 120.39966117491961,
 304.2499408610713,
 11.857540482496573,
 110.26212045419756,
 471.0435826523264,
 911.1831692177522,
 380.1537380486163,
 198.4279650513767,
 138.2325639254577,
 132.70169368170397,
 30.86043568426784,
 185.00525727046374,
 614.8386172231694,
 691.1894564998605,
 1021.884056944431,
 8211.086810923338,
 271.32796828167795,
 398.79650936969915,
 143.13394060122002,
 441.73446137501895,
 837.2266292332857,
 83.22182434383292,
 5.991802896630272,
 91.46738697387852,
 67.59795144327788,
 426.37276331482576,
 98.76933916336499,
 234.34806207700194,
 69.9676833677224,
 744.3866590885578,
 468.18945498862087,
 604.9302633712126,
 1091.5924681217725,
 1375.0317527566745,
 952.010905665984,
 657.5765364710534,
 751.9325689825514,
 184.26892188507773,
 186.09454098636172,
 36.669990002330294,
 94.73809259660277,
 771.9242179146812,
 200.9659509586049,
 188.4617654368014,
 423.83684705505743,
 169.88010031350274,
 336.03202572340393,
 343.19963201006294,
 110.68433241769904,
 915.2329540837186,
 519.0146264767204,
 41.11331662035047,
 198.23499639538224,
 206.2275028865923,
 787.612744004875,
 138.9232927344926,
 1843.6609868486728,
 1028.3924551669104,
 8921.42443413312,
 503.3206989997524,
 395.3391418823591,
 592.3051039917466,
 37.863637730447714,
 1603.3227731751685,
 620.3334979512043,
 79.58506856813999,
 22.99614836390805,
 1051.65402822961,
 157.9031867438626,
 542.0618860105614,
 130.40110733389224,
 524.0601879242034,
 145.05869283911784,
 127.74464321487814,
 902.1806059287094,
 178.17325957535817,
 267.58677427336875,
 221.72842475572702,
 484.0877197840039,
 756.8696225547824,
 215.512964716403,
 704.2786750882849,
 626.1012418631208,
 259.2799394498493,
 19.414852440468223,
 1047.5172741224972,
 46.188178427580844,
 153.71435181206527,
 198.85316574491284,
 337.6267239490985,
 400.8841247380844,
 591.0430883664625,
 894.9565387692579,
 407.9609500630483,
 49.632339250121134,
 257.61403175819055,
 109.25722018871993,
 736.1321901659253,
 334.6350842395091,
 817.1024275514706,
 233.69724349951954,
 993.3246835688377,
 1632.3964471023087,
 455.63343904040164,
 1538.8474905138805,
 512.0789252515947,
 305.77063250952915,
 146.85568515224062,
 51.324058445703045,
 89.33056920127846,
 188.59547792444377,
 43.44421480283834,
 78.35996256158808,
 945.9220386371485,
 451.8697625010943,
 253.52980250851277,
 474.691805230254,
 117.91843166582683,
 180.58024487784334,
 16.22336758917941,
 216.85532606881358,
 149.92265383541968,
 390.0518208129628,
 1166.7682518434087,
 521.67441277194,
 798.0011676446215,
 89.74817195109966,
 79.60398878562644,
 170.991710780593,
 343.11754072566316,
 1516.005051346272,
 45.251819654672616,
 970.2970512821379,
 532.460287455286,
 1517.1432025988065,
 906.5909799153161,
 11.709454322354686,
 452.37392306202673,
 337.77317166916237,
 99.948238720685,
 948.4976563857641,
 509.71613213800316,
 219.15667546525455,
 212.07216095899713,
 37.55445486737436,
 783.6699314322047,
 196.4878707421238,
 489.1729518295438,
 267.3338762302375,
 926.9132368115135,
 104.3292778726154,
 11.709454322354686,
 90.3746275315867,
 20.43233573306089,
 1756.8566334652924,
 276.34805596755814,
 329.1217609398993,
 426.8642205243881,
 101.50724023938577,
 966.5031853399651,
 1010.0783924346331,
 50.93415123618729,
 82.52191163453978,
 236.20619273372145,
 782.987143630776,
 96.70637843345074,
 215.1066538159197,
 619.4774481793585,
 96.70637843345074,
 517.8137807145935,
 744.0043892824099,
 203.71386842792288,
 280.2006444052012,
 797.5326521760237,
 250.9498898153006,
 156.40499499367186,
 76.46297173119515,
 886.342305482883,
 197.4057687769952,
 172.06024319953906,
 37.77984030236506,
 256.172986060868,
 283.0579094119663,
 146.80847144359885,
 231.546780882889,
 806.1558514247873,
 140.4732658512777,
 1038.0325410097873,
 256.1266169708264,
 386.22066231087484,
 130.0731381163175,
 140.09814089239615,
 936.2031955780749,
 408.0600304203969,
 1401.072887206019,
 214.98198759986425,
 304.4888640444734,
 92.60373824150295,
 63.034343958659456,
 1346.0266153815633,
 440.82405691777853,
 306.14226970791685,
 259.1258987657454,
 255.02180166639477,
 599.5700706597947,
 223.06224493624694,
 1233.449966400973,
 97.90295078665488,
 520.0198805814792,
 72.7350083945271,
 1061.7193432742324,
 750.3122581347989,
 26.772065435156073,
 218.55473750063743,
 1131.139392265573,
 663.5445129687997,
 59.78765118441686,
 1431.464789303965,
 156.10610647823924,
 235.83207836246692,
 420.17348477295246,
 260.4734502740888,
 210.81840007245066,
 719.537619011915,
 403.245642038206,
 392.8198393388903,
 212.7840981473199,
 498.826121259938,
 758.6156142687054,
 767.629565225418,
 95.4137849486897,
 313.8324879869224,
 106.06915417411061,
 581.2912708322535,
 384.1951172102264,
 135.48164099584113,
 194.64689447111763,
 186.50108771869373,
 166.6957590063506,
 828.4398522991099,
 73.66661738510152,
 685.7520604101696,
 157.25579035921555,
 1175.1585727862835,
 388.8319859341018,
 195.04841555044845,
 507.91620787024254,
 1042.6150971421923,
 104.33076407382504,
 122.96073734827482,
 134.72307845963948,
 223.6161839686916,
 662.663606604923,
 221.47710068976667,
 1029.827574180122,
 118.50043346399325,
 242.43310261530044,
 742.0621329351263,
 932.0254015439778,
 49.632339250121134,
 462.084680072985,
 74.95645450609487,
 1075.890036489472,
 207220.8628698827,
 330.1517567690849,
 1026.353324569764,
 269.81136688889563,
 1023.7685718868545,
 200.9659509586049,
 1229.3539491420952,
 316.31520852948444,
 887.9148944668791,
 304.91757905587195,
 3620.121920893592,
 558.4223702504934,
 1885.7907484544876,
 98.43782312295325,
 238.01409935560082,
 313.47912170522204,
 139.395373828689,
 463.1397239987798,
 479.2117815151547,
 140.29194685950085,
 655.7174062437886,
 504.05108129073557,
 825.2847778251597,
 100.77904869697068,
 239.97733277254088,
 255.94341180088884,
 334.73580118870075,
 176.25463704154328,
 49.644331011108456,
 425.74258907212686,
 66.54577734358756,
 553.745477878426,
 260.4734502740888,
 400.4058809428928,
 198.09967794445765,
 392.2149813877711,
 547.419852214784,
 1114.1005422262601,
 718.3353679654269,
 503.1329043165217,
 105.3717003054374,
 69.9676833677224,
 1433.021306591402,
 267.4805491890161,
 151.55970235779748,
 640.1907344969068,
 886.5569882639486,
 772.4763070512165,
 185.86300340270728,
 120.28078849896512,
 677.7696064299299,
 92.99136940442699,
 26.27896419077976,
 157.34879522045583,
 23.81328767653649,
 652.3866485021771,
 430.3383635196162,
 229.20556162146852,
 4260.489825028222,
 162.43484500734192,
 110.93100410737534,
 155.7717003890376,
 133.11389421754282,
 119.46098882853593,
 171.03862020900232,
 19.5305330220801,
 162.95952201167677,
 619.6982327135529,
 135.09755203780816,
 300.46473420371433,
 293.6373783991429,
 232.3078978916045,
 553.2436469929934,
 146.86603544441766,
 1224.205325001782,
 651.3007591387347,
 142.57876993439996,
 0.0,
 1139.082466915938,
 979.08791148455,
 888.2763412296729,
 1482.535609099448,
 9.981481558133861,
 538.811763659613,
 203.1614569536953,
 245.8105450215499,
 112.97883019127431,
 91.46314834494287,
 59.64897904847794,
 466.42183578779776,
 497.58902167759857,
 237.08956285556337,
 326.4741260192561,
 78.08280820761298,
 395.59425743040333,
 1110.635549171736,
 105.3717003054374,
 143.69970365971022,
 268.515446842278,
 171.83809214274314,
 165.53254807199323,
 621.9341636657343,
 284.8287147490923,
 299.7830156699815,
 222.96833572497724,
 782.1199797664078,
 426.2710882572543,
 94.65298417436678,
 258.5665325495272,
 503.89613053897625,
 350.11008100296135,
 293.95710558913595,
 1079.0985865108764,
 165.04616650454705,
 268.11023201056537,
 2964.2366874589925,
 258.5665325495272,
 134.03463321909663,
 367.6914681910763,
 461.5543021226347,
 55.34287914617781,
 875.7536393449464,
 177.33247615455645,
 206.28496728864133,
 245.35914973695049,
 21.598852624395914,
 78.87422509178057,
 686.9109560545425,
 186.09454098636172,
 240.17783466028084,
 572.8380034360764,
 258.299025511668,
 500.09899266888885,
 401.63848239613736,
 760.3158971567204,
 639.0960468418067,
 375.065147273907,
 933.0739703762993,
 455.01914395203926,
 266.85437120100084,
 173.5852148882256,
 183.0623529147228,
 421.88471967427057,
 695.725567182734,
 535.8477773279164,
 177441.88989072884,
 455.33894152148355,
 60.700794885839706,
 216.40923360321204,
 308.50050230757563,
 474.90508630921545,
 706.8582270780777,
 384.14493098957837,
 2123.1201082537214,
 354.7644373398243,
 211.77498086694132,
 723.9951515797744,
 181.3801214871433,
 500.6072010597426,
 174.95898841668293,
 1840.337054977286,
 333.35730927234385,
 698.8431631053629,
 472.9120729855896,
 111.40612414433251,
 129.1601405734014,
 861.4739566171424,
 379.98530608786217,
 323.48997123437033,
 276.6965306326054,
 257.07524293189834,
 375.6415909787803,
 209.86303798342698,
 264.7116224359639,
 650.5924073340547,
 687.5403418088983,
 335.5184721215329,
 391.9787440083724,
 243.6990243796095,
 587.0611486922996,
 855.274639540598,
 781.1471936002374,
 1264.2280334798702,
 129.25212883519825,
 391.7709336590967,
 131.46957059856044,
 238.35712710443175,
 294.61155127846735,
 491.7596753198908,
 92.22618653562718,
 267.4805491890161,
 58.58151205422213,
 945.4052601382355,
 180.88257287269192,
 125.16339936271899,
 811.6436536185039,
 577.0558434152862,
 117.91843166582683,
 1113.4520717405612,
 100.62132384703467,
 1081.2490302513393,
 151.69027187076892,
 411.13385338063034,
 772.0033752071108,
 844.2296324799119,
 795.7701990866722,
 251.52441157726957,
 179.57793032288342,
 245.44047760738187,
 543.974590570619,
 627.4335505425352,
 332.7144781288726,
 856.849027109223,
 543.5531900853066,
 1268.3306330708017,
 287.7395214951012,
 692.5723347507202,
 446.1941245727106,
 1217.0199472244744,
 343.850448262766,
 444.23573313509894,
 155.2125938517348,
 276.4595380291365,
 790.3117565160371,
 330.5886717867062,
 624.0798564121419,
 175084.66824847297,
 1307.5249354316147,
 447.2242154220333,
 341.74869917274026,
 598.1670098298738,
 238.29220466832155,
 283.20362175649797,
 235.5498394148321,
 517.545210146907,
 103.21776688558086,
 37.50421857473951,
 226.05962250920672,
 793.641325048449,
 678.2558883824452,
 362.41952815539173,
 222.5885441811054,
 1037.305787309277,
 298.1629045121357,
 497.60587112634585,
 290.9229472267019,
 244.95878016434472,
 166.41967970045087,
 95.54025555889694,
 169.24290988758472,
 538.334705298352,
 208.79732045875502,
 513.6758078453167,
 333.5363289808519,
 784.1370629071437,
 655.029342330115,
 157.8790386128893,
 1708.752000166384,
 235.18652415982405,
 162.62920740156932,
 219.27148127308044,
 645.2633271520064,
 78.09662823874913,
 115.30050474655337,
 428.8415360599694,
 1106.85608297224,
 428.3249417428331,
 144.09018639420447,
 153.5494353224047,
 564.4228762502026,
 182.68130990236455,
 120.3835255282766,
 533.029328014967,
 130.21714177076848,
 318.5406557493396,
 879.1679986165243,
 591.7542279065482,
 423.02847233043815,
 371.220677602628,
 887.8421296617677,
 809.3247593408591,
 243.25428881729334,
 603.110992766853,
 434.8561362757732,
 274.1978406922045,
 348.01837873948733,
 253.85860284416248,
 685.2882338621129,
 827.9618410018746,
 437.0184029114103,
 183.69733472092645,
 120.08069216966169,
 214.65296080757514,
 333.28929188719616,
 1128.539196615728,
 726.4351673579332,
 46.75827170982861,

In [99]:
covid_df['alpha'] = alphas

In [103]:
covid_df.tail()

,date,county,fips,place,confirmed_cases,note,x,y,log_cases,category,ordinal_cat,alpha
1200,2020-10-25,Los Angeles,37.0,Long Beach,13013,NaN,-118.161014,33.805559,9.473704,4,4,1358.941273
1201,2020-10-23,Sacramento,67.0,Sacramento,14476,NaN,-121.494444,38.581667,9.580247,4,4,270.148871
1202,2020-10-25,Santa Clara,85.0,San Jose,15817,NaN,-121.900000,37.333333,9.668841,4,4,242.710237
1203,2020-10-23,Fresno,19.0,Fresno,17052,NaN,-119.766667,36.750000,9.744023,4,4,145.433164
1204,2020-10-25,San Diego,73.0,San Diego,23644,NaN,-117.148962,32.692470,10.070865,4,4,382.697827

In [167]:
covid_df.to_csv('./data/covid_with_alpha.csv', index = False)

#### Now we can use our new alpha column

# Predicting the categorical variable ordinal_cat

In [184]:
X = covid_df[['x', 'y', 'alpha']] # unfortunately adding the alpha overfit it to the training data
y = covid_df['ordinal_cat']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 22)

## KNN

In [185]:
pipe = make_pipeline(StandardScaler(), KNeighborsClassifier())
#pipe = make_pipeline(KNeighborsClassifier())

params = {
    'kneighborsclassifier__n_neighbors': [1, 2, 3],#list(range(5, 25, 2)), #how many decision trees are under the hood
    'kneighborsclassifier__weights': ['uniform'],# 'distance']
}

grid = GridSearchCV(pipe, param_grid = params, cv = 5, n_jobs = -1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('kneighborsclassifier',
                                        KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'kneighborsclassifier__n_neighbors': [1, 2, 3],
                         'kneighborsclassifier__weights': ['uniform']})

In [186]:
grid.score(X_train, y_train)

0.9867109634551495

In [187]:
grid.score(X_test, y_test)

0.3708609271523179

In [188]:
grid.best_params_

{'kneighborsclassifier__n_neighbors': 1,
 'kneighborsclassifier__weights': 'uniform'}

In [189]:
grid.predict_proba(X_test)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

## Random Forests

In [190]:
params = {
    'n_estimators': [100, 200, 500, 1000, 2000], #how many decision trees are under the hood
    'max_depth': [2, 5, 7, 9, 11],
    'min_samples_split': [1, 2, 3, 4],
    'min_samples_leaf': [1, 2, 3]
}
forest = RandomForestClassifier()
grid = GridSearchCV(forest, param_grid = params, cv = 5, n_jobs = -1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 5, 7, 9, 11],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [1, 2, 3, 4],
                         'n_estimators': [100, 200, 500, 1000, 2000]})

In [193]:
grid.score(X_train, y_train)

0.7187153931339978

In [191]:
grid.score(X_test, y_test)

0.3675496688741722

In [192]:
grid.best_params_

{'max_depth': 9,
 'min_samples_leaf': 3,
 'min_samples_split': 4,
 'n_estimators': 100}

# Predicting the continuous variable log_cases

In [118]:
X = covid_df[['x', 'y', 'alpha']]
y = covid_df['log_cases']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 22)

In [ ]:
## Lasso

In [ ]:
pipe = make_pipeline(SelectKBest(f_regression), Lasso()) #NO, select k best does this for selectign number of features